name: 'Obtener versión'
description: 'Obtiene la versión de la aplicación desde un archivo de configuración'

inputs:
  env:  
    description: 'In which environment must this be deployed'
    required: true
    default: 'uat'

outputs:
  version:
    description: 'Versión de la aplicación'
    value: ${{ steps.version_name.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: set version name
      id: version_name
      run:
        output=$(bash ./.github/actions/get-version.sh)
        if [ ${ env } == 'uat' ]; then
          output+="_SNAPSHOT"
        echo "::set-output name=version::$output"
      shell: bash
      
  
