name: Deployment

inputs:
  env:  
    description: 'In which environment must this be deployed'
    required: true
    default: 'uat'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: "$INPUT_ENV"
    steps:
      - name: set env
        env:
          ENV: ${{ inputs.env }}
      - name: download image
        run: docker pull nachocasado/gh_entregable:0.0.0