name: CD Reusable

on:
  workflow_call:
    inputs:
      env:  
        description: 'In which environment must this be deployed'
        required: true
        default: 'production'
        type: string
        
  workflow_run:
    workflows: ["CI Reusable"]
    types:
      - completed

jobs: 
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Obtener version de la aplicación
        id: version
        uses: ./.github/actions/get-version/
        with:
          env: 'production'

      - name: download image
        run: docker pull ${{ secrets.DOCKERHUB_USER }}/gh_entregable:${{ steps.version.outputs.version }}

      - name: docker run
        run: docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USER }}/gh_entregable:${{ steps.version.outputs.version }}

      - name: curl
        run: curl http://localhost:8080
