name: CD Reusable

on:
  workflow_call:
    inputs:
      env:  
        description: 'In which environment must this be deployed'
        required: true
        default: 'production'
        type: string

jobs: 
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Obtener version de la aplicación
        id: version
        uses: ./.github/actions/
        with:
          env: 'production'

      - name: download image
        run: ${{ secrets.DOCKERHUB_USER }}/gh_entregable:${{ steps.version.outputs.version }}

      - name: docker run
        run: docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USER }}/gh_entregable:${{ steps.version.outputs.version }}

      - name: curl
        run: curl http://localhost:8080
