name: CI-CD

on:
  workflow_dispatch:
    inputs:
      env:  
        description: 'In which environment must this be deployed'
        required: true
        default: 'UAT'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obtener version de la aplicación
        id: version
        uses: ./.github/actions/action.yml
        with:
          env: 'uat'         

      - name: Print version
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"
        
      - name: Install dependencies
        run: npm install 

      - name: Construir aplicación de angular
        run: npm run build --prod

      - name: Hacer tests
        run: |
          if [ ${{ inputs.env }} == 'production' ]; then
            sleep 5
            echo "Test pasados adecuadamente"   

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagen de Docker y subirla
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/gh_entregable:${{ steps.version.outputs.version }}

  deployment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:

      - name: download image
        run: ${{ secrets.DOCKERHUB_USER }}/gh_entregable:${{ steps.version.outputs.version }}

      - name: docker run
        run: docker run -d -p 8080:80 ${{ secrets.DOCKERHUB_USER }}/gh_entregable:${{ steps.version.outputs.version }}

      - name: curl
        run: curl http://localhost:8080
