name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obtener version de la aplicación
        id: version
        run: |
          output=$(python ./github./actions/get-version.py)
          echo "::set-output name=version::$output"
        
      - name: Install dependencies
        run: npm install

      - name: Construir aplicación de angular
        run: npm run build --prod

      - name: Construir imagen de Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nachocasado/gh_entregable:${{ steps.version.outputs.version }}