name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obtener version de la aplicación
        id: version
        uses: ./.github/actions/

      - name: Print version
        run: echo "Version: ${{ steps.version.outputs.version }}"
        
      - name: Install dependencies
        run: npm install

      - name: Construir aplicación de angular
        run: npm run build --prod

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagen de Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nachocasado/gh_entregable:${{ steps.version.outputs.version }}
