on:
  pull_request:
    types: [opened, reopened]
    branches: 
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'production'
    steps:

      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Obtener version de la aplicación
        id: version
        uses: ./.github/actions/get-version/
        with:
         target: 'production'    
      
  call_workflow-ci-cd:
    uses: ./.github/workflows/ci-cd-reusable.yml
    with:
      target: 'production'
      env: 'production'
    secrets: inherit
