on:
  pull_request:
    types: [opened, reopened]
    branches: 
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Obtener version de la aplicación
        id: version
        uses: ./.github/actions/action.yml@dev
        with:
          env: 'production'     
      
      - name: ci-cd
        uses: ./.github/workflows/ci-cd.yml@dev
        with:
          env: 'production'  
