on:
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Obtener version de la aplicación
        id: version
        uses: ./.github/actions/action.yml
        with:
          env: 'UAT'     
    
      - name: build-image
        uses: ./.github/actions/ci-cd.yml
        with:
          env: 'UAT'    
    

