on:
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Obtener version de la aplicación
        id: version_name
        uses: ./.github/actions/
        with:
          env: 'UAT'
  call_workdflow_ci-cd:
    uses: ./.github/workflows/ci-cd.yml

        
    
