on:
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Obtener version de la aplicación
        id: version_name
        uses: ./.github/actions/
        with:
          env: 'UAT'     
    
  call_workflow:
    uses: ./.github/workflows/cd-reusable.yml
    with:
      env: 'UAT'
    secrets: inherit
